' Gambas module file

Public $CryptZip As String = "23qP53Xxszqytppz6uRIr9"  ''only for 7z archiving for non-repository
Private $SysConfigPath As String

Public Sub Main()

  If Not Exist(User.Home &/ "healthybit") Then
    Mkdir User.Home &/ "healthybit"
  Endif
  $SysConfigPath = "/etc/healthybit/healthybit.conf"

  ''get setting files
  If Not Exist(User.Home &/ ".config/healthybit") Then
    If Not Exist(User.Home &/ "healthybit" &/ "config.zip") Then
      GetFileFromLocalFTP("https://bitnepal.safiur.com.np/healthybit/Ubuntu22.04/govt/config.zip", User.Home &/ "healthybit", "config.zip")
    Endif
    Exec ["unzip", User.Home &/ "healthybit" &/ "config.zip", "-d", User.Home &/ "healthybit"] Wait
    Print "Uncompressed : " & User.Home &/ "healthybit" &/ "config.zip"
    Shell "cp -a " & User.Home &/ "healthybit" &/ "config" & Space(1) & User.Home &/ ".config/healthybit" Wait
  Endif

  ''get executables
  If Exist(User.Home &/ "healthybit" &/ "healthybit") Then
    Kill User.Home &/ "healthybit" &/ "healthybit"
  Endif
  GetFileFromLocalFTP("https://bitnepal.safiur.com.np/healthybit/Ubuntu22.04/govt/healthybit.zip", User.Home &/ "healthybit", "healthybit.zip")
  If Exist(User.Home &/ "healthybit" &/ "healthybit.zip") Then
    Get7ZExtraction(User.Home &/ "healthybit" &/ "healthybit.zip", $CryptZip, User.Home &/ "healthybit" &/ "healthybit")
  Endif

  If Exist(User.Home &/ "healthybit" &/ "healthybit") Then
    Shell "chmod a+x " & User.Home &/ "healthybit" &/ "healthybit"
    Shell "gnome-terminal" & " -e " & User.Home &/ "healthybit" &/ "healthybit"
  Endif

End

''================= Procedures ==========================
Public Function ShowSettingValue(sFile As String, strSetting As String) As String

  Dim ConfFile As Settings
  Dim strVal As String
  Dim xx As String

  ConfFile = New Settings(sFile)
  strVal = ConfFile[strSetting, Null]
  If strVal Then
    xx = Trim(strVal)
  Else
    xx = ""
  Endif
  Return xx

End

Public Function DecryptSimple(txtoutput As String) As String

  Dim Iw As String
  Dim i As Integer
  Dim a As String
  Dim xx As String

  xx = txtoutput
  Iw = ""
  For i = 0 To (Len(xx) / 3) - 1
    a = CInt(Mid(xx, ((i * 3) + 1), 3))
    Iw = Iw & Chr(a)
  Next

  Return Iw

End

Public Sub GetFileFromLocalFTP(sLink As String, sFolder As String, sFile As String)

  Dim arcmd As String[]

  If Not Exist(sFolder) Then
    Mkdir sFolder
  Endif
  arcmd = ["wget", "--no-cache", "-o", Temp() & ".log", sLink, "-O", sFolder &/ sFile]
  Exec arcmd Wait
  Print "Downloaded : " & sFolder &/ sFile

End

Public Sub Get7ZExtraction(CompressedPath As String, sPassword As String, UnCompressedPath As String)

  Dim xcmd As String

  If System.Exist("7z") Then
    xcmd = "7z x " & CompressedPath & " -p" & sPassword & " -o" & File.Dir(UnCompressedPath)
    Shell xcmd Wait
    Print "Uncompressed : " & CompressedPath
  Endif

End
